services:
  jupyter:
    build:
      context: .
      dockerfile: ./docker/jupyter/Dockerfile
    ports:
      - "8088:8888"
    volumes:
      - ./:/home/jovyan/work
    command: >
      start-notebook.sh --NotebookApp.token='' --NotebookApp.ip=0.0.0.0 --NotebookApp.port=8888 --NotebookApp.allow_root=True

